Models/Declaration.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace RegistrationWeb.Models
{
    public class Declaration
    {
        [Key]
        public int DeclarationId { get; set; }
        [Required]
        [DisplayName("Enter Name in Capital")]
        public string CapitalName { get; set; }
        [Required]
        [DisplayName("Enter today's date")]

        public DateTime signeddate { get; set; }
    }
}

Models/Edu.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace RegistrationWeb.Models
{
    public class Edu
    {
        [Key]
        public int EduId { get; set; }
        [Required]

        [DisplayName("Enter 10th Percentage")]
        public int tenth { get; set; }
        [DisplayName("Enter 10th board")]
        public string? tenthboard { get; set; }
        [Required]

        [DisplayName("Enter 12th Percentage")]
        public int twelth { get; set; }

        [DisplayName("Enter 12th board")]
        public string? twelthboard { get; set; }
        [Required]

        [DisplayName("Enter UG Course name")]
        public string UGCousre { get; set; }
        [Required]
        public string University { get; set; }
        [Required]

        [DisplayName("Enter UG Percentage")]
        public int UG { get; set; }

        [DisplayName("Enter PG Course name")]
        public string? PGCousre { get; set; }

        [DisplayName("University")]
        public string? PGUniversity { get; set; }

        [DisplayName("Enter PG Percentage")]
        public int? PG { get; set; }

        [DisplayName("Enter any project if done")]
        public string? project { get; set; }

        [DisplayName("Self learned course/software if any")]
        public string? software { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace RegistrationWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/PersAss.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace RegistrationWeb.Models
{
    public class PersAss
    {
        [Key]
        public int PersAssId { get; set; }
        [Required]

        [DisplayName("Enter your strengths")]
        public string strength { get; set; }
        [Required]

        [DisplayName("Enter your weaknesses")]
        public string weaknesses { get; set; }

        public string? Hobbies { get; set; }

        public string? Sports { get; set; }


        [DisplayName("Long term goals?")]
        public string? Goals { get; set; }

        [Required]
        [DisplayName("Have you ever attended an interview at any of the MNJ Software Offices across the Globe in the last 6 months? Yes/No (If yes, mention the details)")]
        public string atMNJ { get; set; }
    }
}

Models/Personal.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace RegistrationWeb.Models
{
    public class Personal
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }

        [Required]
        [DisplayName("Father's Name")]

        public string FName { get; set; }
        public string? Nationality { get; set; }

        [Required]
        public DateTime DOB { get; set; }
        public string? Address { get; set; }

        [DisplayName("PAN Number")]
        public string? PAN { get; set; }
        public string? City { get; set; }



        [DisplayName("Mobile Number")]
        public string? mobile { get; set; }
        [Required]
        public string Email { get; set; }

        [DisplayName("Passport Number")]
        public string? Passport { get; set; }
    }
}

Models/PrevEmp.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace RegistrationWeb.Models
{
    public class PrevEmp
    {
        [Key]
        public int PrevEmpId { get; set; }
        [DisplayName("Company Name")]
        public string? CompName { get; set; }

        [DisplayName("Company Address")]
        public string? CompAddress { get; set; }

        [DisplayName("HR Name")]
        public string? HRName { get; set; }

        [DisplayName("HR's Contact")]
        public string? HRMobile { get; set; }

        [DisplayName("HR's email")]
        public string? HREmail { get; set; }

        [DisplayName("Name of Reporting Manager")]
        public string? RepManager { get; set; }

        [DisplayName("Contact of Reporting Manager")]
        public string? ContRepManager { get; set; }

        public string? CTC { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RegistrationWeb.Models;
using System.Diagnostics;

namespace RegistrationWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/RegistrationController.cs
using Microsoft.AspNetCore.Mvc;
using RegistrationWeb.Data;
using RegistrationWeb.Models;
using System;

namespace RegistrationWeb.Controllers
{
	public class RegistrationController : Controller
	{
		private readonly ApplicationDBContext _db;


		public RegistrationController(ApplicationDBContext db)
		{
			_db = db;

		}
		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Personal()     // get
		{
			return View();
		}

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Personal(Personal obj)    //post
        {
            if (ModelState.IsValid)
            {
                _db.Personaltable.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "You personal details are saved go to next step";
                return RedirectToAction("Index");
            }
            TempData["error"] = "Retry";
            return View("Personal");

        }

        public IActionResult Education()     // get
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Education(Edu obj)    //post
        {
            if (ModelState.IsValid)
            {
                _db.Edutable.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "You educational details are saved go to next step";
                return RedirectToAction("Index");
            }
            TempData["error"] = "Retry";
            return View("Education");

        }

        public IActionResult PrevEmp()     // get
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult PrevEmp(PrevEmp obj)    //post
        {
            if (ModelState.IsValid)
            {
                _db.PrevEmptable.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Your Previous Employer details are saved go to next step";
                return RedirectToAction("Index");
            }
            TempData["error"] = "Retry";
            return View("PrevEmp");

        }

        public IActionResult Assessment()     // get
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Assessment(PersAss obj)    //post
        {
            if (ModelState.IsValid)
            {
                _db.PersAsstable.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Your Personal Assessment details are saved go to next step";
                return RedirectToAction("Index");
            }
            TempData["error"] = "Retry";
            return View("Assessment");

        }

        public IActionResult Declaration()     // get
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Declaration(Declaration obj)    //post
        {
            if (ModelState.IsValid)
            {
                _db.Declarationtable.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Your Registration is done successfully, now you can close this window";
                return RedirectToAction("Index");
            }
            TempData["error"] = "Retry";
            return View("Declaration");

        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
	<h1 class="display-4">Welcome</h1>

	<span>
		Thank you for the interest shown in our company. Please take a few minutes of your time to
		fill details by clicking onto below button and help us understand your technical skills and personal
		competencies better.
	</span>
	<div>

		<br />

		<a asp-controller="Registration" asp-action="Index" class="btn btn-primary" style="width:150px">
			Go to Registration
		</a>
	</div>
</div>
>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RegistrationWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RegistrationWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RegistrationWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Registration" asp-action="Index">Registration</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - RegistrationWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <h2>@TempData["success"]</h2>
}

@if (TempData["error"] != null)
{
    <h2>@TempData["error"]</h2>
}